openapi: 3.0.3
info:
  title: API example
  description: API example declaration
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      description: Home
      operationId: default
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: OK
  /hello:
    get:
      description: Returns a personalized hello world greeting
      operationId: hello
      parameters:
        - name: name
          required: false
          in: query
          description: A name to use for personalization
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'

components:
  schemas:
    Hello:
      required:
        - message
      properties:
        message:
          type: string